name: 'cuda'
description: 'Installs CUDA and adds it to PATH'
author: 'Jim Verheijde'
inputs:
  cuda:
    description: 'Cuda version'
    required: false
    default: '11.2.1'
runs:
  using: 'node12'
  main: dist/index.js
