name: 'cuda'
description: 'Installs CUDA and adds it to PATH'
author: 'Jim Verheijde'
inputs:
  cuda:
    description: 'Cuda version'
    required: false
    default: '11.0.167'
  visual_studio:
    description: 'Visual Studio version (Windows only)'
    required: false
    default: 'Visual Studio 16 2019'
runs:
  using: 'node12'
  main: dist/index.js
