name: 'cuda'
description: 'Installs CUDA and adds it to PATH'
author: 'Jim Verheijde'
inputs:
  cuda:
    description: 'Cuda version'
    required: false
    default: '11.2.2'
  subPackages:
    description: 'Only installs specified subpackages, must be in the form of a JSON array. For example, if you only want to install nvcc and visual studio integration: "[''nvcc'', ''visual_studio_integration'']"'
    required: false
    default: '[]'
  method:
    description: "Right now only 'local' is implemented. Installation method, can be either 'local' or 'network'. 'local' downloads the entire installer with all packages and runs that (you can still only install certain packages with subPackages). 'network' downloads a smaller executable which only downloads necessary packages which you can define in subPackages"
    required: false
    default: 'local'
runs:
  using: 'node12'
  main: dist/index.js
